# HTTP

@host = http://localhost:3000/api
@json = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGIxN2NkZDI0N2ZmMzczZjFlM2MwZmEiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidGVzdEB0ZXN0LnJ1IiwiaWF0IjoxNzU2NDYzODIwLCJleHAiOjE3NTY0Njc0MjB9.Fw24QqteXRt4vkfjXyN7kAOvM2svyi9nFlsPywZzPa8


### Создать черновик (возвращает { "id": "..." })
POST {{host}}/programs/draft
Content-Type: {{json}}
Authorization: Bearer {{token}}

{}

### Список всех программ (по createdAt убыв.)
GET {{host}}/programs

### Только черновики
GET {{host}}/programs?status=draft

### Сортировка по популярности (views)
GET {{host}}/programs?sortByViews=true

### Пагинация
GET {{host}}/programs?limit=10&offset=0